# Generated by Django 4.1.7 on 2024-04-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_lead'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
